apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: syncconfigs.myoperator.example.com
spec:
  group: myoperator.example.com
  names:
    kind: SyncConfig
    listKind: SyncConfigList
    plural: syncconfigs
    singular: syncconfig
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sourceCluster:
                  type: string
                targetClusters:
                  type: array
                  items:
                    type: string
                namespaces:
                  type: array
                  items:
                    type: string
                resources:
                  type: array
                  items:
                    type: object
                    properties:
                      kind:
                        type: string
                      name:
                        type: string
                namespaceHandling:
                  type: string
                  enum: ["create", "fail"]
